version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

submodules:
  include:
    - build123d
  recursive: true

sphinx:
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: ./build123d
      extra_requirements:
        - docs
    - requirements: requirements.txt
