version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

submodules:
  include:
    - build123d
  recursive: true

sphinx:
  configuration: conf.py

python:
  install:
    - method: pip
      path: ./build123d
      extra_requirements:
        - docs
    - requirements: requirements.txt
